version: '3'
services:
  # Build a container for Redmine that depends on the DB container.
  # The wait-for-it [1] script is used to wait for the DB container to
  # start before launching Rails -- otherwise Rails will throw an
  # exception if it can't connect to the DB.
  #
  # [1] https://github.com/vishnubob/wait-for-it
  redmine-production:
    build: .
    depends_on:
      - db-production
    volumes:
      - .:/redmine
    ports:
      - '8080:3000'
    environment:
      SECRET_KEY_BASE: 31e7c6400f7af1dd4faab7f10f6ff38f71bf9a34
    command: ["./bin/wait-for-it", "db-production:5432", "--", "./bin/run"]

  # Create a PostgreSQL container with a default DB named
  # 'redmine_production'.
  db-production:
    image: postgres:11.0
    volumes:
      - db-production:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: redmine

# Persistent volume for the DB
volumes:
  db-production:
