version: '3'
services:
  # Build a container for Redmine that depends on the DB container.
  # The wait-for-it [1] script is used to wait for the DB container to
  # start before launching Rails -- otherwise Rails will throw an
  # exception if it can't connect to the DB.
  #
  # [1] https://github.com/vishnubob/wait-for-it
  redmine:
    build: .
    depends_on:
      - db
    volumes:
      - .:/redmine
    environment:
      SECRET_KEY_BASE: 31e7c6400f7af1dd4faab7f10f6ff38f71bf9a34
    command: ["./bin/wait-for-it", "db:5432", "--", "./bin/run"]

  # Create a PostgreSQL container with a default DB named
  # 'redmine_production'.
  db:
    image: postgres:11.0
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: redmine

  # Create an Nginx container with read-only access to its configuration
  # file and SSL certs.
  nginx:
    image: nginx:1.14.0
    depends_on:
      - redmine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - '80:80'
      - '443:443'

# Persistent volume for the DB
volumes:
  db:
