production:
  adapter: postgresql
  database: redmine
  host: db
  username: postgres
  password: ""
  encoding: utf8

development:
  adapter: postgresql
  database: redmine_development
  host: db-development
  username: postgres
  password: ""
  encoding: utf8
